// Auto-generated parametric anchor points
// Generated by scripts/generate-parametric-anchors.js

export interface AnchorPoint {
  x: number;
  y: number;
  rotation: number;
  scale: number;
  label?: string;
}

export interface BreakpointAnchors {
  mobile: AnchorPoint[];   // < 768px
  tablet: AnchorPoint[];   // 768px - 1024px
  desktop: AnchorPoint[];  // > 1024px
}

export interface ProductAnchorData {
  id: string;
  category: string;
  imageUrl: string;
  anchors: BreakpointAnchors;
  center: { x: number; y: number };
}

export const PRODUCT_ANCHORS: Record<string, ProductAnchorData> = {
  "classic-loop": {
    id: "classic-loop",
    category: "bracelets",
    imageUrl: "/bracelets/Classic Loop bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "lustre-link": {
    id: "lustre-link",
    category: "bracelets",
    imageUrl: "/bracelets/Lustre Link bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "dual-link": {
    id: "dual-link",
    category: "bracelets",
    imageUrl: "/bracelets/Dual Link Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "paper-clip": {
    id: "paper-clip",
    category: "bracelets",
    imageUrl: "/bracelets/paper clip bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":78,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":75.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":75.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":67.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":67.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":55.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":55.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":40.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":40.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "golden-charm": {
    id: "golden-charm",
    category: "bracelets",
    imageUrl: "/bracelets/Golden Charm Chain Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":80,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":77.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":77.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":69.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":69.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":57.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":57.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":42.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":42.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "luxe-chain": {
    id: "luxe-chain",
    category: "bracelets",
    imageUrl: "/bracelets/Luxe Chain Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":82,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":79.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":79.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":71.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":71.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":59.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":59.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":44.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":44.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "monochrome-braid": {
    id: "monochrome-braid",
    category: "bracelets",
    imageUrl: "/bracelets/Monochrome Braid Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "neon-twist": {
    id: "neon-twist",
    category: "bracelets",
    imageUrl: "/bracelets/Neon Twist Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "ocean-weave": {
    id: "ocean-weave",
    category: "bracelets",
    imageUrl: "/bracelets/Ocean Weave Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "skyline-braid": {
    id: "skyline-braid",
    category: "bracelets",
    imageUrl: "/bracelets/Skyline Braid Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "twist-elegance": {
    id: "twist-elegance",
    category: "bracelets",
    imageUrl: "/bracelets/Twist Elegance Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "verdant-braid": {
    id: "verdant-braid",
    category: "bracelets",
    imageUrl: "/bracelets/Verdant Braid Bracelet.png",
    anchors: {
      mobile: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":84,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":81.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":81.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":73.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":73.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":61.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":61.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":46.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":46.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
  "chain-01": {
    id: "chain-01",
    category: "necklace",
    imageUrl: "/necklace/Paperclip Link Necklace.png",
    anchors: {
      mobile: [{"x":50,"y":67.5,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":64.79,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":64.79,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":56.97,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":56.97,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":45,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":45,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":30.31,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":30.31,"rotation":82.19,"scale":1.5,"label":"p8"}], 
      tablet: [{"x":50,"y":70,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":67.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":67.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":59.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":59.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":47.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":47.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":32.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":32.81,"rotation":82.19,"scale":1.5,"label":"p8"}],
      desktop: [{"x":50,"y":70,"rotation":0,"scale":1.5,"label":"p0"},{"x":61.97,"y":67.29,"rotation":-25.08,"scale":1.5,"label":"p1"},{"x":38.03,"y":67.29,"rotation":25.08,"scale":1.5,"label":"p2"},{"x":72.5,"y":59.47,"rotation":-47.17,"scale":1.5,"label":"p3"},{"x":27.5,"y":59.47,"rotation":47.17,"scale":1.5,"label":"p4"},{"x":80.31,"y":47.5,"rotation":-65.82,"scale":1.5,"label":"p5"},{"x":19.69,"y":47.5,"rotation":65.82,"scale":1.5,"label":"p6"},{"x":84.47,"y":32.81,"rotation":-82.19,"scale":1.5,"label":"p7"},{"x":15.53,"y":32.81,"rotation":82.19,"scale":1.5,"label":"p8"}]
    },
    center: { x: 0.5, y: 0.5 }
  },
};
