const fs = require('fs');
const path = require('path');

// --- CONFIGURATION ---
// Directories to scan for images (relative to project root)
const SCAN_DIRS = [
    'public/bracelets',
    'public/necklace' // Add 'public/charms' here if needed
];

// Output file path
const OUTPUT_FILE = path.join(__dirname, '../lib/anchor.ts');

// --- HELPER FUNCTIONS ---

// Generate the TypeScript entry for a single product
const generateEntry = (id, webPath, category) => {
    return `  "${id}": {
    id: "${id}",
    category: "${category}",
    imageUrl: "${webPath}",
    // Run the anchor-tool to populate these points
    anchors: [], 
    center: { x: 0.5, y: 0.5 } 
  }`;
};

// --- MAIN SCRIPT ---
console.log('🚀 Starting Anchor Scaffold...');

let allEntries = [];

SCAN_DIRS.forEach(dirRelative => {
    const fullPath = path.join(__dirname, '..', dirRelative);

    if (!fs.existsSync(fullPath)) {
        console.warn(`⚠️  Warning: Directory not found: ${dirRelative}`);
        return;
    }

    const category = path.basename(dirRelative); // e.g., 'bracelets'
    const files = fs.readdirSync(fullPath).filter(file => /\.(png|jpg|jpeg|webp)$/i.test(file));

    console.log(`📂 Scanning ${dirRelative}... Found ${files.length} images.`);

    files.forEach(file => {
        // ID strategy: use filename without extension (e.g., 'gold-chain.png' -> 'gold-chain')
        const id = path.parse(file).name;
        const webPath = `/${category}/${file}`; // e.g., '/bracelets/gold-chain.png'

        allEntries.push(generateEntry(id, webPath, category));
    });
});

if (allEntries.length === 0) {
    console.error('❌ No images found in any directories. Aborting.');
    process.exit(1);
}

// Construct the final file content
const fileContent = `// This file is auto-generated by scripts/scaffold-anchors.js
// Do not manually edit the structure, only the coordinate values.

export interface AnchorPoint {
  x: number;
  y: number;
  label?: string;
  type?: 'curve' | 'point'; // Optional: if you need to distinguish types
}

export interface ProductAnchorData {
  id: string;
  category: string;
  imageUrl: string;
  anchors: AnchorPoint[];
  center: { x: number; y: number };
}

export const PRODUCT_ANCHORS: Record<string, ProductAnchorData> = {
${allEntries.join(',\n')}
};
`;

// Write the file
fs.writeFileSync(OUTPUT_FILE, fileContent);

console.log('------------------------------------------------');
console.log(`✅ Success! Generated lib/anchor.ts with ${allEntries.length} products.`);
console.log(`👉 Next: Restart your server and go to /admin/anchor-tool`);